[variables]
APP_ENV = "production"
APP_DEBUG = "false"  
DB_CONNECTION = "pgsql"
DB_HOST = "aws-1-eu-west-3.pooler.supabase.com"
DB_PORT = "6543"
DB_DATABASE = "postgres"
DB_USERNAME = "postgres.phkcrceolwwzgakfvcms"
DB_PASSWORD = "Wissem2002."
APP_URL = "https://senerentcar-production.up.railway.app"
FRONTEND_URL = "https://senerentcar.vercel.app"

[phases.setup]
aptPkgs = ["php8.2", "php8.2-pgsql", "php8.2-mbstring", "php8.2-gd", "php8.2-zip", "php8.2-bcmath", "php8.2-curl", "php8.2-xml"]
nixPkgs = ["composer"]

[phases.install]
cmds = [
    "composer install --optimize-autoloader --no-dev"
]

[phases.build]
cmds = [
    "php artisan migrate --force",
    "php artisan db:seed --force"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"