[variables]
DB_CONNECTION = "mysql"
DB_HOST = "${MYSQL_HOST}"
DB_PORT = "${MYSQL_PORT}"
DB_DATABASE = "${MYSQL_DATABASE}"
DB_USERNAME = "${MYSQL_USER}"
DB_PASSWORD = "${MYSQL_PASSWORD}"

[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo_mysql", "php82Extensions.mbstring", "php82Extensions.gd", "php82Extensions.zip", "php82Extensions.bcmath", "composer"]

[phases.install]
cmds = [
    "composer install --optimize-autoloader --no-dev"
]

[phases.build]
cmds = [
    "php artisan migrate --force",
    "php artisan db:seed --force"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"