[variables]
APP_ENV = "production"
APP_DEBUG = "true"
APP_KEY = "base64:ii/Hf8Tfyd9BaCByj8ZpT/4ONdLgTRJ/d2B67p785NI="
DB_CONNECTION = "mysql"
DB_HOST = "${MYSQLHOST}"
DB_PORT = "${MYSQLPORT}"
DB_DATABASE = "${MYSQLDATABASE}"
DB_USERNAME = "${MYSQLUSER}"
DB_PASSWORD = "${MYSQLPASSWORD}"

[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo_mysql", "php82Extensions.mbstring", "php82Extensions.gd", "php82Extensions.zip", "php82Extensions.bcmath", "composer"]

[phases.install]
cmds = [
    "composer install --optimize-autoloader --no-dev"
]

[phases.build]
cmds = [
    "echo 'Environment variables check:'",
    "echo 'MYSQLHOST='$MYSQLHOST",
    "echo 'MYSQLPORT='$MYSQLPORT", 
    "echo 'MYSQLDATABASE='$MYSQLDATABASE",
    "echo 'MYSQLUSER='$MYSQLUSER",
    "echo 'PORT='$PORT",
    "php artisan migrate --force",
    "php artisan db:seed --force"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"