[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo_mysql", "php82Extensions.mysqli", "php82Extensions.mbstring", "php82Extensions.gd", "php82Extensions.zip", "php82Extensions.bcmath", "composer"]

[phases.install]
cmds = [
    "composer install --optimize-autoloader --no-dev"
]

[phases.build]
cmds = [
    "php artisan migrate --force",
    "php artisan db:seed --force"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"