[build]
buildCommand = "composer install --optimize-autoloader --no-dev && chmod +x start.sh"

[deploy]
startCommand = "chmod +x start.sh && ./start.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
APP_ENV = "production"
APP_DEBUG = "false"
LOG_CHANNEL = "errorlog"
LOG_LEVEL = "error"
QUEUE_CONNECTION = "database"
SESSION_DRIVER = "database"
CACHE_DRIVER = "database"

[environments.production.build]
buildCommand = "composer install --optimize-autoloader --no-dev && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan migrate --force && php artisan db:seed --force"