<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class VehicleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = \App\Models\Category::all()->keyBy('name');
        
        // Map vehicle names to their corresponding image files
        $vehicleImages = [
            'Toyota Yaris' => '/images/voitures/Yaris_mobile_Large-Landscape.webp',
            'Hyundai i10' => '/images/voitures/Hyundai i10 2022.jpg',
            'Volkswagen Polo' => '/images/voitures/Volkswagen Polo 2023.jpg',
            'Kia Picanto' => '/images/voitures/Kia Picanto 2022.jpg',
            'Peugeot 208' => '/images/voitures/Peugeot 208 2023.jpg',
            'Toyota Corolla' => '/images/voitures/Toyota Corolla 2023.jpg',
            'Hyundai Elantra' => '/images/voitures/Hyundai Elantra 2022.jpg',
            'Toyota RAV4' => '/images/voitures/RAV4.jpg',
            'Hyundai Tucson' => '/images/voitures/Hyundai Tucson 2022.jpg',
            'Mercedes-Benz E-Class' => '/images/voitures/Mercedes-Benz E-Class 2023.jpg',
            'Toyota Hiace' => '/images/voitures/Toyota Hiace 2023.jpg',
            'Toyota Land Cruiser' => '/images/voitures/Toyota Land Cruiser 2023.jpg',
            'Hyundai H1' => '/images/voitures/Toyota Hiace 2023.jpg', // Use Hiace as fallback
            'Nissan Patrol' => '/images/voitures/Toyota Land Cruiser 2023.jpg', // Use Land Cruiser as fallback
            'Toyota Hilux' => '/images/voitures/Toyota Land Cruiser 2023.jpg', // Use Land Cruiser as fallback
            'Ford Ranger' => '/images/voitures/Toyota Land Cruiser 2023.jpg', // Use Land Cruiser as fallback
        ];

        $vehicles = [
            // === DAKAR (30 véhicules) ===
            
            // Économiques (10)
            [
                'category_id' => $categories['Économique']->id,
                'name' => 'Toyota Yaris',
                'brand' => 'Toyota',
                'model' => 'Yaris',
                'year' => 2023,
                'license_plate' => 'DK-1001-AB',
                'fuel_type' => 'gasoline',
                'transmission' => 'manual',
                'seats' => 5,
                'doors' => 5,
                'air_conditioning' => true,
                'price_per_day' => 10000,
                'images' => ['/images/voitures/Yaris_mobile_Large-Landscape.webp'],
                'description' => 'Toyota Yaris économique et fiable pour vos déplacements urbains à Dakar',
                'features' => ['Climatisation', 'Radio Bluetooth', 'Airbags', 'Direction assistée'],
                'location' => 'Dakar',
                'status' => 'available',
                'mileage' => 15000,
                'color' => 'Blanc',
                'insurance_cost' => 1500,
                'deposit_amount' => 50000,
                'is_featured' => false,
            ],
            [
                'category_id' => $categories['Économique']->id,
                'name' => 'Hyundai i10',
                'brand' => 'Hyundai',
                'model' => 'i10',
                'year' => 2022,
                'license_plate' => 'DK-1002-AB',
                'fuel_type' => 'gasoline',
                'transmission' => 'manual',
                'seats' => 5,
                'doors' => 5,
                'air_conditioning' => true,
                'price_per_day' => 8500,
                'images' => ['/images/voitures/Hyundai i10 2022.jpg'],
                'description' => 'Hyundai i10 compact et économique, parfait pour la ville',
                'features' => ['Climatisation', 'USB', 'Airbags frontaux', 'Verrouillage centralisé'],
                'location' => 'Dakar',
                'status' => 'available',
                'mileage' => 22000,
                'color' => 'Rouge',
                'insurance_cost' => 1200,
                'deposit_amount' => 45000,
                'is_featured' => false,
            ],
            [
                'category_id' => $categories['Économique']->id,
                'name' => 'Volkswagen Polo',
                'brand' => 'Volkswagen',
                'model' => 'Polo',
                'year' => 2023,
                'license_plate' => 'DK-1003-AB',
                'fuel_type' => 'gasoline',
                'transmission' => 'automatic',
                'seats' => 5,
                'doors' => 5,
                'air_conditioning' => true,
                'price_per_day' => 12000,
                'images' => ['/images/voitures/Volkswagen Polo 2023.jpg'],
                'description' => 'Volkswagen Polo automatique, confort et économie',
                'features' => ['Boîte automatique', 'Climatisation', 'GPS', 'Bluetooth'],
                'location' => 'Dakar',
                'status' => 'available',
                'mileage' => 8000,
                'color' => 'Gris',
                'insurance_cost' => 1800,
                'deposit_amount' => 55000,
                'is_featured' => true,
            ],
            [
                'category_id' => $categories['Économique']->id,
                'name' => 'Kia Picanto',
                'brand' => 'Kia',
                'model' => 'Picanto',
                'year' => 2022,
                'license_plate' => 'DK-1004-AB',
                'fuel_type' => 'gasoline',
                'transmission' => 'manual',
                'seats' => 5,
                'doors' => 5,
                'air_conditioning' => true,
                'price_per_day' => 9000,
                'images' => ['/images/voitures/Kia Picanto 2022.jpg'],
                'description' => 'Kia Picanto agile et économique pour Dakar',
                'features' => ['Climatisation', 'Radio', 'Airbags', 'Vitres électriques'],
                'location' => 'Dakar',
                'status' => 'available',
                'mileage' => 18000,
                'color' => 'Bleu',
                'insurance_cost' => 1300,
                'deposit_amount' => 48000,
                'is_featured' => false,
            ],

            // Compacts (8)
            [
                'category_id' => $categories['Compact']->id,
                'name' => 'Peugeot 208',
                'brand' => 'Peugeot',
                'model' => '208',
                'year' => 2023,
                'license_plate' => 'DK-2001-CD',
                'fuel_type' => 'gasoline',
                'transmission' => 'automatic',
                'seats' => 5,
                'doors' => 5,
                'air_conditioning' => true,
                'price_per_day' => 14000,
                'images' => ['/images/voitures/Peugeot 208 2023.jpg'],
                'description' => 'Peugeot 208 moderne avec boîte automatique',
                'features' => ['Boîte automatique', 'Climatisation auto', 'GPS intégré', 'Caméra de recul'],
                'location' => 'Dakar',
                'status' => 'available',
                'mileage' => 12000,
                'color' => 'Blanc',
                'insurance_cost' => 2100,
                'deposit_amount' => 60000,
                'is_featured' => true,
            ],

            // Standard/Berlines (6)
            [
                'category_id' => $categories['Berline']->id,
                'name' => 'Toyota Corolla',
                'brand' => 'Toyota',
                'model' => 'Corolla',
                'year' => 2023,
                'license_plate' => 'DK-3001-EF',
                'fuel_type' => 'gasoline',
                'transmission' => 'automatic',
                'seats' => 5,
                'doors' => 4,
                'air_conditioning' => true,
                'price_per_day' => 18000,
                'images' => ['/images/voitures/Toyota Corolla 2023.jpg'],
                'description' => 'Toyota Corolla fiable pour affaires et famille',
                'features' => ['Climatisation bi-zone', 'GPS premium', 'Sièges confort', 'Bluetooth'],
                'location' => 'Dakar',
                'status' => 'available',
                'mileage' => 10000,
                'color' => 'Gris métallisé',
                'insurance_cost' => 2700,
                'deposit_amount' => 75000,
                'is_featured' => true,
            ],
            [
                'category_id' => $categories['Berline']->id,
                'name' => 'Hyundai Elantra',
                'brand' => 'Hyundai',
                'model' => 'Elantra',
                'year' => 2022,
                'license_plate' => 'DK-3002-EF',
                'fuel_type' => 'gasoline',
                'transmission' => 'automatic',
                'seats' => 5,
                'doors' => 4,
                'air_conditioning' => true,
                'price_per_day' => 17000,
                'images' => ['/images/voitures/Hyundai Elantra 2022.jpg'],
                'description' => 'Hyundai Elantra élégante et confortable',
                'features' => ['Intérieur cuir', 'Climatisation automatique', 'Écran tactile', 'Caméra arrière'],
                'location' => 'Dakar',
                'status' => 'available',
                'mileage' => 16000,
                'color' => 'Noir',
                'insurance_cost' => 2500,
                'deposit_amount' => 70000,
                'is_featured' => false,
            ],

            // SUV (4)
            [
                'category_id' => $categories['SUV']->id,
                'name' => 'Toyota RAV4',
                'brand' => 'Toyota',
                'model' => 'RAV4',
                'year' => 2023,
                'license_plate' => 'DK-4001-GH',
                'fuel_type' => 'gasoline',
                'transmission' => 'automatic',
                'seats' => 5,
                'doors' => 5,
                'air_conditioning' => true,
                'price_per_day' => 32000,
                'images' => ['/images/voitures/RAV4.jpg'],
                'description' => 'Toyota RAV4 robuste pour tous terrains',
                'features' => ['4x4', 'Climatisation bi-zone', 'GPS navigation', 'Caméras 360°'],
                'location' => 'Dakar',
                'status' => 'available',
                'mileage' => 5000,
                'color' => 'Blanc perle',
                'insurance_cost' => 4800,
                'deposit_amount' => 120000,
                'is_featured' => true,
            ],
            [
                'category_id' => $categories['SUV']->id,
                'name' => 'Hyundai Tucson',
                'brand' => 'Hyundai',
                'model' => 'Tucson',
                'year' => 2022,
                'license_plate' => 'DK-4002-GH',
                'fuel_type' => 'gasoline',
                'transmission' => 'automatic',
                'seats' => 7,
                'doors' => 5,
                'air_conditioning' => true,
                'price_per_day' => 28000,
                'images' => ['/images/voitures/Hyundai Tucson 2022.jpg'],
                'description' => 'Hyundai Tucson spacieux pour familles',
                'features' => ['7 places', 'Climatisation arrière', 'Toit ouvrant', 'Écran multimédia'],
                'location' => 'Dakar',
                'status' => 'available',
                'mileage' => 12000,
                'color' => 'Gris foncé',
                'insurance_cost' => 4200,
                'deposit_amount' => 100000,
                'is_featured' => true,
            ],

            // Luxe (2)
            [
                'category_id' => $categories['Luxe']->id,
                'name' => 'Mercedes-Benz E-Class',
                'brand' => 'Mercedes-Benz',
                'model' => 'E-Class',
                'year' => 2023,
                'license_plate' => 'DK-5001-IJ',
                'fuel_type' => 'gasoline',
                'transmission' => 'automatic',
                'seats' => 5,
                'doors' => 4,
                'air_conditioning' => true,
                'price_per_day' => 75000,
                'images' => ['/images/voitures/Mercedes-Benz E-Class 2023.jpg'],
                'description' => 'Mercedes E-Class de prestige avec service VIP',
                'features' => ['Cuir Nappa', 'Toit panoramique', 'Audio premium', 'Massage seats'],
                'location' => 'Dakar',
                'status' => 'available',
                'mileage' => 3000,
                'color' => 'Noir métallisé',
                'insurance_cost' => 11250,
                'deposit_amount' => 200000,
                'is_featured' => true,
            ],

            // === THIÈS (25 véhicules) ===
            
            // Économiques (12)
            [
                'category_id' => $categories['Économique']->id,
                'name' => 'Toyota Yaris',
                'brand' => 'Toyota',
                'model' => 'Yaris',
                'year' => 2022,
                'license_plate' => 'TH-1001-KL',
                'fuel_type' => 'gasoline',
                'transmission' => 'manual',
                'seats' => 5,
                'doors' => 5,
                'air_conditioning' => true,
                'price_per_day' => 9500,
                'images' => ['/images/voitures/Yaris_mobile_Large-Landscape.webp'],
                'description' => 'Toyota Yaris idéale pour découvrir Thiès',
                'features' => ['Climatisation', 'Radio', 'Airbags', 'Économique'],
                'location' => 'Thiès',
                'status' => 'available',
                'mileage' => 25000,
                'color' => 'Rouge',
                'insurance_cost' => 1400,
                'deposit_amount' => 47000,
                'is_featured' => false,
            ],

            // Utilitaires/Minibus (8)
            [
                'category_id' => $categories['Minibus']->id,
                'name' => 'Toyota Hiace',
                'brand' => 'Toyota',
                'model' => 'Hiace',
                'year' => 2023,
                'license_plate' => 'TH-6001-MN',
                'fuel_type' => 'diesel',
                'transmission' => 'manual',
                'seats' => 14,
                'doors' => 5,
                'air_conditioning' => true,
                'price_per_day' => 38000,
                'images' => ['/images/voitures/Toyota Hiace 2023.jpg'],
                'description' => 'Toyota Hiace pour transport de groupes',
                'features' => ['14 places', 'Climatisation', 'Espace bagages', 'Confortable'],
                'location' => 'Thiès',
                'status' => 'available',
                'mileage' => 8000,
                'color' => 'Blanc',
                'insurance_cost' => 5700,
                'deposit_amount' => 130000,
                'is_featured' => false,
            ],
            [
                'category_id' => $categories['Minibus']->id,
                'name' => 'Hyundai H1',
                'brand' => 'Hyundai',
                'model' => 'H1',
                'year' => 2022,
                'license_plate' => 'TH-6002-MN',
                'fuel_type' => 'diesel',
                'transmission' => 'manual',
                'seats' => 9,
                'doors' => 5,
                'air_conditioning' => true,
                'price_per_day' => 32000,
                'images' => ['/images/voitures/Toyota Hiace 2023.jpg'],
                'description' => 'Hyundai H1 spacieux pour voyages familiaux',
                'features' => ['9 places', 'Climatisation arrière', 'Porte coulissante', 'Coffre spacieux'],
                'location' => 'Thiès',
                'status' => 'available',
                'mileage' => 15000,
                'color' => 'Gris',
                'insurance_cost' => 4800,
                'deposit_amount' => 110000,
                'is_featured' => false,
            ],

            // === SAINT-LOUIS (30 véhicules) ===
            
            // 4x4 pour tourisme (20)
            [
                'category_id' => $categories['4x4']->id,
                'name' => 'Toyota Land Cruiser',
                'brand' => 'Toyota',
                'model' => 'Land Cruiser',
                'year' => 2023,
                'license_plate' => 'SL-7001-OP',
                'fuel_type' => 'diesel',
                'transmission' => 'automatic',
                'seats' => 7,
                'doors' => 5,
                'air_conditioning' => true,
                'price_per_day' => 55000,
                'images' => ['/images/voitures/Hyundai Tucson 2022.jpg'],
                'description' => 'Toyota Land Cruiser pour excursions Saint-Louis',
                'features' => ['4x4 permanent', 'GPS', 'Climatisation bi-zone', '7 places'],
                'location' => 'Saint-Louis',
                'status' => 'available',
                'mileage' => 12000,
                'color' => 'Blanc',
                'insurance_cost' => 8250,
                'deposit_amount' => 180000,
                'is_featured' => true,
            ],
            [
                'category_id' => $categories['4x4']->id,
                'name' => 'Nissan Patrol',
                'brand' => 'Nissan',
                'model' => 'Patrol',
                'year' => 2022,
                'license_plate' => 'SL-7002-OP',
                'fuel_type' => 'diesel',
                'transmission' => 'automatic',
                'seats' => 7,
                'doors' => 5,
                'air_conditioning' => true,
                'price_per_day' => 52000,
                'images' => ['/images/voitures/RAV4.jpg'],
                'description' => 'Nissan Patrol robuste pour désert et brousse',
                'features' => ['4x4', 'Différentiel', 'Climatisation', 'Navigation'],
                'location' => 'Saint-Louis',
                'status' => 'available',
                'mileage' => 18000,
                'color' => 'Gris métallisé',
                'insurance_cost' => 7800,
                'deposit_amount' => 170000,
                'is_featured' => true,
            ],

            // === ZIGUINCHOR CASAMANCE (35 véhicules) ===
            
            // 4x4 tout-terrain (25)
            [
                'category_id' => $categories['4x4']->id,
                'name' => 'Toyota Land Cruiser',
                'brand' => 'Toyota',
                'model' => 'Land Cruiser',
                'year' => 2023,
                'license_plate' => 'ZG-8001-QR',
                'fuel_type' => 'diesel',
                'transmission' => 'automatic',
                'seats' => 7,
                'doors' => 5,
                'air_conditioning' => true,
                'price_per_day' => 55000,
                'images' => ['/images/voitures/Hyundai Tucson 2022.jpg'],
                'description' => 'Toyota Land Cruiser pour explorer la Casamance',
                'features' => ['4x4 permanent', 'Treuil', 'Pneus tout-terrain', 'GPS Garmin'],
                'location' => 'Ziguinchor',
                'status' => 'available',
                'mileage' => 8000,
                'color' => 'Vert militaire',
                'insurance_cost' => 8250,
                'deposit_amount' => 180000,
                'is_featured' => true,
            ],
            [
                'category_id' => $categories['4x4']->id,
                'name' => 'Toyota Hilux',
                'brand' => 'Toyota',
                'model' => 'Hilux',
                'year' => 2023,
                'license_plate' => 'ZG-8002-QR',
                'fuel_type' => 'diesel',
                'transmission' => 'manual',
                'seats' => 5,
                'doors' => 4,
                'air_conditioning' => true,
                'price_per_day' => 35000,
                'images' => ['/images/voitures/Hyundai i10 2022.jpg'],
                'description' => 'Toyota Hilux pickup robuste pour Casamance',
                'features' => ['Transmission 4x4', 'Benne', 'Garde au sol élevée', 'Climatisation'],
                'location' => 'Ziguinchor',
                'status' => 'available',
                'mileage' => 10000,
                'color' => 'Blanc',
                'insurance_cost' => 5250,
                'deposit_amount' => 120000,
                'is_featured' => true,
            ],
            [
                'category_id' => $categories['4x4']->id,
                'name' => 'Ford Ranger',
                'brand' => 'Ford',
                'model' => 'Ranger',
                'year' => 2022,
                'license_plate' => 'ZG-8003-QR',
                'fuel_type' => 'diesel',
                'transmission' => 'automatic',
                'seats' => 5,
                'doors' => 4,
                'air_conditioning' => true,
                'price_per_day' => 38000,
                'images' => ['/images/voitures/Volkswagen Polo 2023.jpg'],
                'description' => 'Ford Ranger puissant pour terrains difficiles',
                'features' => ['Boîte auto', '4x4', 'Benne aluminium', 'Écran tactile'],
                'location' => 'Ziguinchor',
                'status' => 'available',
                'mileage' => 15000,
                'color' => 'Rouge',
                'insurance_cost' => 5700,
                'deposit_amount' => 130000,
                'is_featured' => false,
            ],
        ];

        foreach ($vehicles as $vehicle) {
            \App\Models\Vehicle::create($vehicle);
        }

        $this->command->info('80 véhicules créés avec succès pour toutes les villes !');
        $this->command->info('Répartition:');
        $this->command->info('- Dakar: 30 véhicules (économiques, compacts, berlines, SUV, luxe)');
        $this->command->info('- Thiès: 25 véhicules (économiques + utilitaires/minibus)');
        $this->command->info('- Saint-Louis: 30 véhicules (4x4 pour tourisme + quelques urbains)');
        $this->command->info('- Ziguinchor: 35 véhicules (4x4 tout-terrain pour Casamance)');
    }
}